#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).
# shellcheck disable=SC2086
get_domains() {
    subs=('web-01' 'web-02' 'lb-01' 'www')
    local param_1="$1"
    local param_2="$2"
    if [ "$param_2" ]; then
        dig "$param_2.$param_1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain $param_2 is a" + $4 + $5}'
        return
    fi
    for sub in "${subs[@]}"; do
        dig "$sub.$param_1" | grep -A1 'ANSWER SECTION:'
    done
}
get_domains $1 $2