#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
scp -o StrictHostKeyChecking=no -i ~/.ssh/school $1 ubuntu@18.204.14.40:~/
# mysql-bin.000170 |      737 

# CHANGE MASTER TO
# MASTER_HOST='54.145.85.177',
# MASTER_USER='replica_user',
# MASTER_PASSWORD='projectcorrection280hbtn',
# MASTER_LOG_FILE='mysql-bin.000170',
# MASTER_LOG_POS=737;