#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

sudo sed -i "s|server_name _;|server_name _;\n\trewrite /redirect_me https://www.youtube.com permanent;|" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart