#!/usr/bin/env bash
# Double the number of webservers
#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i 's|server_name _;|server_name _;\n\tadd_header X-Served-By "299585-web-01";|' /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart

