#!/usr/bin/env bash
# Double the number of webservers
# shellcheck disable=SC2154
sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

sudo sed -i 's|server_name _;|server_name _;\n\tadd_header X-Served-By $HOSTNAME;|' /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart

