#!/usr/bin/env bash
# Double the number of webservers
sudo apt-get update
sudo apt-get install -y haproxy

echo "frontend nandom_front" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tbind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tdefault_backend nandom_back" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "backend nandom_back" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tbalance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tserver 299585-web-01 54.145.85.177:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tserver 299585-web-02 100.25.17.121:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
