#!/usr/bin/env bash
# Double the number of webservers
# shellcheck disable=SC2154
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*

sudo service haproxy start

echo "frontend nandom_front\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "\tbind *:80\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "\tdefault_backend nandom_back\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "backend nandom_back\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "\tbalance roundrobin\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "\tserver web-01 54.145.85.177:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "\tserver web-02 100.25.17.121:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
