#!/usr/bin/env bash
# 0. Nginx likes port 80
rm /etc/nginx/sites-enabled/default
sudo sed -i 's|listen [::]:80 default_server ipv6only=on;|listen [::]:80 default_server;|' /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart