#!/usr/bin/env bash
# 0. Nginx likes port 80
sed -i 's|ipv6only=on||' /etc/nginx/sites-available/default
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo service nginx restart