#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour=0
min=1
while [ $hour -le "12" ]
do
        echo "Hour: $hour"
        while [ $min -le "59" ]
        do
                echo $min
                (("$min+=1"))
        done
        min=1
        (("$hour+=1"))
done